Repository ywoo-srin-minj/spring_study, pull requests merged in 2022-02, with the labels that each got.

#2 [add] 설명 위한 커밋
  src/main/java/com/second/spring_study/SpringStudyApplication.java
Labels: setting

#5 (#3) 기본 파일 세팅
  build.gradle
  src/main/java/controller/user_minj_controller.java
  src/main/java/entity/user_minj/User.java
  src/main/java/entity/user_minj/repository/UserRepository.java
  src/main/java/service/user_minj_service.java
Labels: setting

#7 (#3)기본 파일 세팅
  build.gradle
  src/main/java/com/second/spring_study/controller/user_srin_controller.java
  src/main/java/com/second/spring_study/entity/user_srin/User.java
  src/main/java/com/second/spring_study/entity/user_srin/repository/UserRepository.java
  src/main/java/com/second/spring_study/service/user_srin_service.java
Labels: setting

#14 (#4) User 엔티티 설계 - 연우
  build.gradle
  src/main/java/entity/user_ywoo/User.java
Labels: feature

#13 (#4) user 엔티티 설계 - 민지
  src/main/java/entity/user_minj/User.java
Labels: feature

#15 (#4)User 엔티티 설계 - 세린
  build.gradle
  src/main/java/com/second/spring_study/entity/user_srin/User.java
Labels: feature

#17 (#8) 회원 추가 기능 구현 - 연우
  src/main/java/com/second/spring_study/controller/UserYwooController.java
  src/main/java/com/second/spring_study/controller/user_ywoo_controller.java
  src/main/java/com/second/spring_study/dto/request/ywoo/UserRequestDto.java
  src/main/java/com/second/spring_study/entity/user_minj/UserMinj.java
  src/main/java/com/second/spring_study/entity/user_minj/repository/UserMinjRepository.java
  src/main/java/com/second/spring_study/entity/user_minj/repository/UserRepository.java
  src/main/java/com/second/spring_study/entity/user_srin/UserSrin.java
  src/main/java/com/second/spring_study/entity/user_srin/repository/UserRepository.java
  src/main/java/com/second/spring_study/entity/user_srin/repository/UserSrinRepository.java
  src/main/java/com/second/spring_study/entity/user_ywoo/UserYwoo.java
  src/main/java/com/second/spring_study/entity/user_ywoo/repository/UserRepository.java
  src/main/java/com/second/spring_study/entity/user_ywoo/repository/UserYwooRepository.java
  src/main/java/com/second/spring_study/service/UserYwooService.java
  src/main/java/com/second/spring_study/service/user_ywoo_service.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/second/spring_study/SpringStudyApplicationTests.java
Labels: feature

#16 (#8) 회원 추가 기능 구현 - 민지
  src/main/java/com/second/spring_study/controller/UserMinjController.java
  src/main/java/com/second/spring_study/controller/user_minj_controller.java
  src/main/java/com/second/spring_study/dto/request/minj/UserRequestDto.java
  src/main/java/com/second/spring_study/entity/user_minj/UserMinj.java
  src/main/java/com/second/spring_study/entity/user_minj/repository/UserMinjRepository.java
  src/main/java/com/second/spring_study/service/UserMinjService.java
  src/main/java/com/second/spring_study/service/user_minj_service.java
Labels: feature

#18 (#8) 회원 추가 기능 구현 - 세린
  src/main/java/com/second/spring_study/controller/UserSrinController.java
  src/main/java/com/second/spring_study/controller/user_srin_controller.java
  src/main/java/com/second/spring_study/dto/request/srin/UserRequestDto.java
  src/main/java/com/second/spring_study/entity/user_srin/UserSrin.java
  src/main/java/com/second/spring_study/entity/user_srin/repository/UserSrinRepository.java
  src/main/java/com/second/spring_study/service/UserSrinService.java
  src/main/java/com/second/spring_study/service/user_srin_service.java
Labels: feature

#21 (#12) 회원 삭제 기능 구현 - 세린
  build.gradle
  src/main/java/com/second/spring_study/controller/UserSrinController.java
  src/main/java/com/second/spring_study/entity/user_srin/UserSrin.java
  src/main/java/com/second/spring_study/entity/user_srin/repository/UserSrinRepository.java
  src/main/java/com/second/spring_study/service/UserSrinService.java
Labels: feature

#22 (#9) 회원 전체 조회 구현 - 민지
  src/main/java/com/second/spring_study/controller/UserMinjController.java
  src/main/java/com/second/spring_study/dto/response/minj/UserResponseDto.java
  src/main/java/com/second/spring_study/service/UserMinjService.java
Labels: feature

#24 (#9) 회원 전체 조회 구현 - 세린
  src/main/java/com/second/spring_study/controller/UserSrinController.java
  src/main/java/com/second/spring_study/dto/request/srin/UserResponseDto.java
  src/main/java/com/second/spring_study/service/UserSrinService.java
Labels: feature

#23 (#9) 회원 전체 조회 기능 구현 - 연우
  src/main/java/com/second/spring_study/controller/UserYwooController.java
  src/main/java/com/second/spring_study/dto/reponse/ywoo/UserResponseDto.java
  src/main/java/com/second/spring_study/service/UserYwooService.java
Labels: feature

#28 (#11) 회원 상세 조회 구현 - 세린
  src/main/java/com/second/spring_study/controller/UserSrinController.java
  src/main/java/com/second/spring_study/dto/request/srin/UserResponseDto.java
  src/main/java/com/second/spring_study/dto/response/srin/UserResponseDto.java
  src/main/java/com/second/spring_study/service/UserSrinService.java
Labels: feature

#32 (#10) 회원 수정 구현 - 연우
  src/main/java/com/second/spring_study/controller/UserYwooController.java
  src/main/java/com/second/spring_study/dto/request/ywoo/UserRequestUpdateDto.java
  src/main/java/com/second/spring_study/entity/user_ywoo/UserYwoo.java
  src/main/java/com/second/spring_study/entity/user_ywoo/repository/UserYwooRepository.java
  src/main/java/com/second/spring_study/entity/user_ywoo/repository/UserYwooRepositoryExtension.java
  src/main/java/com/second/spring_study/entity/user_ywoo/repository/UserYwooRepositoryImpl.java
  src/main/java/com/second/spring_study/service/UserYwooService.java
Labels: feature

#31 (#10) 회원 수정 기능 구현 - 세린
  src/main/java/com/second/spring_study/controller/UserSrinController.java
  src/main/java/com/second/spring_study/dto/request/srin/UserUpdateRequestDto.java
  src/main/java/com/second/spring_study/entity/user_srin/UserSrin.java
  src/main/java/com/second/spring_study/entity/user_srin/repository/UserSrinRepository.java
  src/main/java/com/second/spring_study/entity/user_srin/repository/UserSrinRepositoryExtension.java
  src/main/java/com/second/spring_study/entity/user_srin/repository/UserSrinRepositoryImpl.java
  src/main/java/com/second/spring_study/service/UserSrinService.java
Labels: feature

#33 (#26) Controller 예외 처리 - 민지
  src/main/java/com/second/spring_study/controller/UserMinjController.java
  src/main/java/com/second/spring_study/dto/request/minj/UpdateUserRequestDto.java
  src/main/java/com/second/spring_study/dto/request/minj/UserRequestDto.java
  src/main/java/com/second/spring_study/dto/response/minj/ErrorResponse.java
  src/main/java/com/second/spring_study/dto/response/minj/UserResponseDto.java
  src/main/java/com/second/spring_study/entity/user_minj/UserMinj.java
  src/main/java/com/second/spring_study/entity/user_minj/repository/UserMinjRepository.java
  src/main/java/com/second/spring_study/entity/user_minj/repository/UserMinjRepositoryImpl.java
  src/main/java/com/second/spring_study/exception/minj/ApiException.java
  src/main/java/com/second/spring_study/exception/minj/ApiExceptionAdvice.java
  src/main/java/com/second/spring_study/exception/minj/ErrorCodeEnum.java
  src/main/java/com/second/spring_study/service/UserMinjService.java
Labels: exception

#34 (#26) 전역 에러 처리 - 연우
  src/main/java/com/second/spring_study/dto/request/ywoo/UserRequestDto.java
  src/main/java/com/second/spring_study/dto/request/ywoo/UserRequestUpdateDto.java
  src/main/java/com/second/spring_study/dto/response/ywoo/ErrorResponse.java
  src/main/java/com/second/spring_study/dto/response/ywoo/UserResponseDto.java
  src/main/java/com/second/spring_study/entity/user_ywoo/UserYwoo.java
  src/main/java/com/second/spring_study/entity/user_ywoo/repository/UserYwooRepository.java
  src/main/java/com/second/spring_study/entity/user_ywoo/repository/UserYwooRepositoryImpl.java
  src/main/java/com/second/spring_study/exception/ywoo/ApiException.java
  src/main/java/com/second/spring_study/exception/ywoo/ApiExceptionAdvice.java
  src/main/java/com/second/spring_study/exception/ywoo/DataNoFoundException.java
  src/main/java/com/second/spring_study/exception/ywoo/ErrorCodeEnum.java
  src/main/java/com/second/spring_study/service/UserYwooService.java
  src/main/resources/application.yml
Labels: exception

#36 (#27) UserController 통합 테스트 코드 작성
  src/main/java/com/second/spring_study/exception/minj/ApiExceptionAdviceMinj.java
  src/main/java/com/second/spring_study/exception/srin/ApiExceptionAdviceSrin.java
  src/main/java/com/second/spring_study/exception/ywoo/ApiExceptionAdviceYwoo.java
  src/main/resources/application.yml
  src/test/java/com/second/spring_study/controller/UserMinjControllerTest.java
  src/test/resources/application.yml
  src/test/resources/data.sql
  src/test/resources/table.sql
Labels: test

#37 (#27) UserController 통합 테스트 코드 작성 - 세린
  src/test/java/com/second/spring_study/controller/UserSrinControllerTest.java
Labels: test

#48 (#39) Board 엔티티 설계 - 연우
  src/main/java/com/second/spring_study/SpringStudyApplication.java
  src/main/java/com/second/spring_study/dto/response/ywoo/UserResponseDto.java
  src/main/java/com/second/spring_study/entity/BaseEntity.java
  src/main/java/com/second/spring_study/entity/ywoo/boardYwoo/BoardYwoo.java
  src/main/java/com/second/spring_study/entity/ywoo/boardYwoo/repository/BoardYwooRepository.java
  src/main/java/com/second/spring_study/entity/ywoo/userYwoo/UserYwoo.java
  src/main/java/com/second/spring_study/entity/ywoo/userYwoo/repository/UserYwooRepository.java
  src/main/java/com/second/spring_study/entity/ywoo/userYwoo/repository/UserYwooRepositoryExtension.java
  src/main/java/com/second/spring_study/entity/ywoo/userYwoo/repository/UserYwooRepositoryImpl.java
  src/main/java/com/second/spring_study/service/UserYwooService.java
Labels: feature

#51 (#40) 게시글 추가 기능 구현 - 민지
  src/main/java/com/second/spring_study/controller/PostMinjController.java
  src/main/java/com/second/spring_study/dto/request/minj/CreatePostRequestDto.java
  src/main/java/com/second/spring_study/entity/minj/boardMinj/BoardMinj.java
  src/main/java/com/second/spring_study/entity/minj/boardMinj/repository/BoardRepository.java
  src/main/java/com/second/spring_study/entity/minj/postMinj/PostMinj.java
  src/main/java/com/second/spring_study/entity/minj/postMinj/repository/PostRepository.java
  src/main/java/com/second/spring_study/entity/minj/userMinj/UserMinj.java
  src/main/java/com/second/spring_study/entity/minj/userMinj/repository/UserMinjRepositoryImpl.java
  src/main/java/com/second/spring_study/entity/srin/user_srin/repository/UserSrinRepositoryImpl.java
  src/main/java/com/second/spring_study/service/PostMinjService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: feature

#50 (#40) 게시글 추가 기능 구현 - 세린
  src/main/java/com/second/spring_study/controller/PostSrinController.java
  src/main/java/com/second/spring_study/dto/request/srin/PostCreateRequestDto.java
  src/main/java/com/second/spring_study/entity/srin/BoardSrin.java
  src/main/java/com/second/spring_study/entity/srin/post_srin/PostSrin.java
  src/main/java/com/second/spring_study/entity/srin/post_srin/repository/PostSrinRepository.java
  src/main/java/com/second/spring_study/entity/srin/user_srin/UserSrin.java
  src/main/java/com/second/spring_study/service/PostSrinService.java
Labels: feature

#52 (#40) 게시글 추가 기능 구현 - 연우
  src/main/java/com/second/spring_study/controller/PostYwooController.java
  src/main/java/com/second/spring_study/dto/request/ywoo/PostRequestCreateDto.java
  src/main/java/com/second/spring_study/entity/ywoo/boardYwoo/BoardYwoo.java
  src/main/java/com/second/spring_study/entity/ywoo/boardYwoo/PostYwoo.java
  src/main/java/com/second/spring_study/entity/ywoo/boardYwoo/repository/BoardYwooRepository.java
  src/main/java/com/second/spring_study/entity/ywoo/boardYwoo/repository/PostYwooRepository.java
  src/main/java/com/second/spring_study/entity/ywoo/userYwoo/UserYwoo.java
  src/main/java/com/second/spring_study/service/PostYwooService.java
  src/main/resources/application.yml
Labels: feature

#53 (#41) 게시글 전체 및 상세 조회 기능 구현 - 민지
  src/main/java/com/second/spring_study/controller/post/PostMinjController.java
  src/main/java/com/second/spring_study/dto/response/minj/PostResponseDto.java
  src/main/java/com/second/spring_study/entity/minj/postMinj/PostMinj.java
  src/main/java/com/second/spring_study/entity/minj/userMinj/repository/UserMinjRepositoryExtension.java
  src/main/java/com/second/spring_study/entity/minj/userMinj/repository/UserMinjRepositoryImpl.java
  src/main/java/com/second/spring_study/exception/minj/ErrorCodeEnum.java
  src/main/java/com/second/spring_study/service/post/PostMinjService.java
Labels: feature

#55 (#41) 게시글 전체 및 상세 조회 기능 구현 - 연우
  src/main/java/com/second/spring_study/controller/post/PostYwooController.java
  src/main/java/com/second/spring_study/dto/response/ywoo/PostFindResponseDto.java
  src/main/java/com/second/spring_study/entity/ywoo/userYwoo/repository/UserYwooRepositoryExtension.java
  src/main/java/com/second/spring_study/entity/ywoo/userYwoo/repository/UserYwooRepositoryImpl.java
  src/main/java/com/second/spring_study/exception/ywoo/ErrorCodeEnum.java
  src/main/java/com/second/spring_study/service/post/PostYwooService.java
Labels: feature

#54 (#41) 게시글 전체 및 상세 조회 기능 구현 - 세린
  src/main/java/com/second/spring_study/controller/post/PostSrinController.java
  src/main/java/com/second/spring_study/dto/response/srin/PostInquiryResponseDto.java
  src/main/java/com/second/spring_study/entity/srin/post_srin/PostSrin.java
  src/main/java/com/second/spring_study/entity/srin/user_srin/repository/UserSrinRepositoryExtension.java
  src/main/java/com/second/spring_study/entity/srin/user_srin/repository/UserSrinRepositoryImpl.java
  src/main/java/com/second/spring_study/exception/srin/ErrorCodeEnum.java
  src/main/java/com/second/spring_study/service/post/PostSrinService.java
Labels: feature

#56 (#43, #44) 게시글 수정 및 삭제 기능 구현 - 연우
  src/main/java/com/second/spring_study/controller/post/PostYwooController.java
  src/main/java/com/second/spring_study/dto/request/ywoo/PostRequestDto.java
  src/main/java/com/second/spring_study/entity/ywoo/boardYwoo/PostYwoo.java
  src/main/java/com/second/spring_study/service/post/PostYwooService.java
Labels: feature

#58 (#43) 게시글 수정 기능 구현 - 민지
  src/main/java/com/second/spring_study/controller/post/PostMinjController.java
  src/main/java/com/second/spring_study/dto/request/minj/PostRequestDto.java
  src/main/java/com/second/spring_study/entity/minj/postMinj/PostMinj.java
  src/main/java/com/second/spring_study/service/post/PostMinjService.java
Labels: feature

#57 (#44) 게시글 삭제 기능 구현 - 세린
  src/main/java/com/second/spring_study/controller/post/PostSrinController.java
  src/main/java/com/second/spring_study/service/post/PostSrinService.java
Labels: feature

#60 (#43) 게시글 수정 기능 구현 - 세린
  src/main/java/com/second/spring_study/controller/post/PostSrinController.java
  src/main/java/com/second/spring_study/dto/request/srin/PostUpdateRequestDto.java
  src/main/java/com/second/spring_study/entity/srin/post_srin/PostSrin.java
  src/main/java/com/second/spring_study/service/post/PostSrinService.java
Labels: feature

#59 (#44) 게시글 삭제 기능 구현 - 민지
  src/main/java/com/second/spring_study/controller/post/PostMinjController.java
  src/main/java/com/second/spring_study/service/post/PostMinjService.java
Labels: feature

#61 (#45) Post Controller 테스트 - 민지
  src/test/java/com/second/spring_study/controller/post/PostMinjControllerTest.java
  src/test/resources/application.yml
  src/test/resources/data.sql
Labels: test

#63 (#45) Post Controller 테스트 코드 작성 - 세린
  src/main/java/com/second/spring_study/controller/post/PostSrinController.java
  src/main/java/com/second/spring_study/dto/request/srin/PostCreateRequestDto.java
  src/main/java/com/second/spring_study/dto/request/srin/PostRequestDto.java
  src/main/java/com/second/spring_study/entity/srin/post_srin/PostSrin.java
  src/main/java/com/second/spring_study/service/post/PostSrinService.java
  src/test/java/com/second/spring_study/controller/post/PostSrinControllerTest.java
  src/test/java/com/second/spring_study/controller/user/UserMinjControllerTest.java
  src/test/java/com/second/spring_study/controller/user/UserSrinControllerTest.java
  src/test/java/com/second/spring_study/controller/user/UserYwooControllerTest.java
  src/test/resources/application.yml
  src/test/resources/data.sql
  src/test/resources/table.sql
Labels: test

#65 (#45) Controller 통합 테스트 코드 작성 - 연우
  src/main/java/com/second/spring_study/controller/post/PostYwooController.java
  src/main/java/com/second/spring_study/dto/response/ywoo/PostFindResponseDto.java
  src/main/java/com/second/spring_study/entity/ywoo/postYwoo/PostYwoo.java
  src/main/java/com/second/spring_study/entity/ywoo/postYwoo/repository/PostYwooRepository.java
  src/main/java/com/second/spring_study/entity/ywoo/userYwoo/UserYwoo.java
  src/main/java/com/second/spring_study/entity/ywoo/userYwoo/repository/UserYwooRepositoryImpl.java
  src/main/java/com/second/spring_study/service/post/PostYwooService.java
  src/test/java/com/second/spring_study/controller/post/PostYwooControllerTest.java
  src/test/resources/data.sql
  src/test/resources/table.sql
Labels: test
